server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:nytdacm_oa_dev}
    username: ${PG_USER:nytdacm_oa}
    password: ${PG_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=3s
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

sa-token:
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # jwt 密钥
  jwt-secret-key: ${JWT_SECRET_KEY:JzNuZP2nGuBnTQKe3A0rxuYhExezSghw}
  # token有效期
  token-expire-timeout: ${TOKEN_EXPIRE_TIMEOUT:604800}
  # 关闭 Cookie 功能
  is-read-cookie: false
  is-write-header: false

file:
  upload-dir: ${UPLOAD_DIR:/tmp/oa/}
