name: deploy

on: workflow_dispatch

env:
  TZ: Asia/Shanghai

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://nytdacm.com
    if: github.repository == 'nytdacm-dev/oa'
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: web/pnpm-lock.yaml
      - name: Build frontend
        run: |
          cd web
          pnpm install
          pnpm run build
      - name: Copy frontend
        run: |
          mkdir -p src/main/resources/static
          cp -r web/dist/* src/main/resources/static
      - name: Build backend
        uses: gradle/gradle-build-action@v2
        with:
          arguments: thinJar
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        run: bash -e ./bin/deploy.sh
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
